name: mobile_testcase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  date_time_picker: 2.1.0
  dropdown_button2: 1.7.2
  dropdown_search: 5.0.2
  flutter:
    sdk: flutter
  flutter_datetime_picker: 1.5.1
  get: 4.6.5
  http: ^0.13.5
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
